# Generated by Django 4.1 on 2022-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_posts_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
