# Generated by Django 4.1 on 2022-09-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
    ]
